### ISSUE TITLE
IP set CREATES a HUSK WIFI

### ISSUE THREAD

**Issue by revdeluxe** [mkdirlove/ANTI-PISO-WIFI#4]
### WHAT IS HUSK WIFI
**Basically it's a copy of your WIFI target that you've successfully 'Hijacked' it basically easy to fix but the ping 8.8.8.8 should not be there unless you've successfully reset-ted your connection.**

_i haven't really played alot with the code, also i don't want to make this issue too deep also perhaps just a reminder of having it there to be solve _by me or someone else.__

### OTHER MATTERS
> **Petition to PISO WIFI database sniffer(If you really want to own the WiFi, this is your chance.)**
> **Logging should be in a swap/temp format especially if you want to see whats happening when doing a scan**
> _Even if it feels useless, it's useful if you want to name who owns this IP & MAC_

**Comment by revdeluxe** [comment]
@mkdirlove something weird is happening with the scan. because it's detecting false bytes. perhaps by the log that is not removed from the DIR. i suggest putting a check scan on the TMP folder. If you have better idea of solving this please reply.
![editme](https://user-images.githubusercontent.com/38414584/164040344-acf2e390-e839-44fb-b72f-0645b3c9248f.png)
I'm Using FISH, but i run the file with BASH. not problem at first but yeah this just arouse recently.

**Comment by zbtcm** [comment]
how do you run this in Git?

**Comment by revdeluxe** [comment]
> how do you run this in Git?

I dunno what you mean but
You'll need to install sipcalc first.

git clone <address>
bash <filename>

**Comment by ianhmanuel** [comment]
when I install sipcalc, it says package not found.
