### ISSUE TITLE
38: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by ianhmanuel** [mkdirlove/ANTI-PISO-WIFI#8]
$ sudo ./anti-piso-wifi.sh
nl80211 not found.
./anti-piso-wifi.sh: 38: Syntax error: "(" unexpected

**Comment by mkdirlove** [comment]
to tool is obsolete / deprecated.
please use other tool

**Comment by ianhmanuel** [comment]
what tool can use? are there any others?
